#############################################################################
# Makefile for building: expressioneditor
# Generated by qmake (2.01a) (Qt 4.6.0) on: Mon Dec 7 15:40:49 2009
# Project:  expressioneditor.pro
# Template: app
# Command: /home/alex/qtsdk-2009.05/qt/bin/qmake -spec ../../../qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile expressioneditor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../qtsdk-2009.05/qt/mkspecs/linux-g++ -I. -I../../../qtsdk-2009.05/qt/include/QtCore -I../../../qtsdk-2009.05/qt/include/QtGui -I../../../qtsdk-2009.05/qt/include/QtXml -I../../../qtsdk-2009.05/qt/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/alex/qtsdk-2009.05/qt/lib
LIBS          = $(SUBLIBS)  -L/home/alex/qtsdk-2009.05/qt/lib -lQtXml -L/home/alex/qtsdk-2009.05/qt/lib -lQtGui -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/alex/qtsdk-2009.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		welcome.cpp \
		expressioneditor.cpp \
		expressiontester.cpp \
		expressionhighlighter.cpp \
		graphicaleditor.cpp \
		graphicaltoolkit.cpp \
		graphicalworkspace.cpp \
		graphicalexpression.cpp \
		textgraphicsitem.cpp \
		alternativesgraphicsitem.cpp \
		groupinggraphicsitem.cpp \
		charrangegraphicsitem.cpp \
		repeatgraphicsitem.cpp \
		specialchargraphicsitem.cpp moc_mainwindow.cpp \
		moc_welcome.cpp \
		moc_expressioneditor.cpp \
		moc_expressiontester.cpp \
		moc_expressionhighlighter.cpp \
		moc_graphicaleditor.cpp \
		moc_graphicaltoolkit.cpp \
		moc_graphicalworkspace.cpp \
		qrc_images.cpp
OBJECTS       = main.o \
		mainwindow.o \
		welcome.o \
		expressioneditor.o \
		expressiontester.o \
		expressionhighlighter.o \
		graphicaleditor.o \
		graphicaltoolkit.o \
		graphicalworkspace.o \
		graphicalexpression.o \
		textgraphicsitem.o \
		alternativesgraphicsitem.o \
		groupinggraphicsitem.o \
		charrangegraphicsitem.o \
		repeatgraphicsitem.o \
		specialchargraphicsitem.o \
		moc_mainwindow.o \
		moc_welcome.o \
		moc_expressioneditor.o \
		moc_expressiontester.o \
		moc_expressionhighlighter.o \
		moc_graphicaleditor.o \
		moc_graphicaltoolkit.o \
		moc_graphicalworkspace.o \
		qrc_images.o
DIST          = ../../../qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		../../../qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		../../../qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		../../../qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		expressioneditor.pro
QMAKE_TARGET  = expressioneditor
DESTDIR       = 
TARGET        = expressioneditor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: expressioneditor.pro  ../../../qtsdk-2009.05/qt/mkspecs/linux-g++/qmake.conf ../../../qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		../../../qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		../../../qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		../../../qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		/home/alex/qtsdk-2009.05/qt/lib/libQtXml.prl \
		/home/alex/qtsdk-2009.05/qt/lib/libQtCore.prl \
		/home/alex/qtsdk-2009.05/qt/lib/libQtGui.prl
	$(QMAKE) -spec ../../../qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile expressioneditor.pro
../../../qtsdk-2009.05/qt/mkspecs/common/g++.conf:
../../../qtsdk-2009.05/qt/mkspecs/common/unix.conf:
../../../qtsdk-2009.05/qt/mkspecs/common/linux.conf:
../../../qtsdk-2009.05/qt/mkspecs/qconfig.pri:
../../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/debug.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/qt.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/moc.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/resources.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/uic.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/lex.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf:
/home/alex/qtsdk-2009.05/qt/lib/libQtXml.prl:
/home/alex/qtsdk-2009.05/qt/lib/libQtCore.prl:
/home/alex/qtsdk-2009.05/qt/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../qtsdk-2009.05/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile expressioneditor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/expressioneditor1.0.0 || $(MKDIR) .tmp/expressioneditor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/expressioneditor1.0.0/ && $(COPY_FILE) --parents mainwindow.hpp welcome.hpp expressioneditor.hpp expressiontester.hpp expressionhighlighter.hpp graphicaleditor.hpp graphicaltoolkit.hpp graphicalworkspace.hpp graphicalexpression.hpp textgraphicsitem.hpp alternativesgraphicsitem.hpp groupinggraphicsitem.hpp charrangegraphicsitem.hpp repeatgraphicsitem.hpp specialchargraphicsitem.hpp .tmp/expressioneditor1.0.0/ && $(COPY_FILE) --parents images.qrc .tmp/expressioneditor1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp welcome.cpp expressioneditor.cpp expressiontester.cpp expressionhighlighter.cpp graphicaleditor.cpp graphicaltoolkit.cpp graphicalworkspace.cpp graphicalexpression.cpp textgraphicsitem.cpp alternativesgraphicsitem.cpp groupinggraphicsitem.cpp charrangegraphicsitem.cpp repeatgraphicsitem.cpp specialchargraphicsitem.cpp .tmp/expressioneditor1.0.0/ && (cd `dirname .tmp/expressioneditor1.0.0` && $(TAR) expressioneditor1.0.0.tar expressioneditor1.0.0 && $(COMPRESS) expressioneditor1.0.0.tar) && $(MOVE) `dirname .tmp/expressioneditor1.0.0`/expressioneditor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/expressioneditor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_welcome.cpp moc_expressioneditor.cpp moc_expressiontester.cpp moc_expressionhighlighter.cpp moc_graphicaleditor.cpp moc_graphicaltoolkit.cpp moc_graphicalworkspace.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_welcome.cpp moc_expressioneditor.cpp moc_expressiontester.cpp moc_expressionhighlighter.cpp moc_graphicaleditor.cpp moc_graphicaltoolkit.cpp moc_graphicalworkspace.cpp
moc_mainwindow.cpp: welcome.hpp \
		expressioneditor.hpp \
		graphicaleditor.hpp \
		graphicaltoolkit.hpp \
		graphicalworkspace.hpp \
		graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp \
		expressiontester.hpp \
		expressionhighlighter.hpp \
		mainwindow.hpp
	/home/alex/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.hpp -o moc_mainwindow.cpp

moc_welcome.cpp: welcome.hpp
	/home/alex/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) welcome.hpp -o moc_welcome.cpp

moc_expressioneditor.cpp: graphicaleditor.hpp \
		graphicaltoolkit.hpp \
		graphicalworkspace.hpp \
		graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp \
		expressiontester.hpp \
		expressionhighlighter.hpp \
		expressioneditor.hpp
	/home/alex/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) expressioneditor.hpp -o moc_expressioneditor.cpp

moc_expressiontester.cpp: expressiontester.hpp
	/home/alex/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) expressiontester.hpp -o moc_expressiontester.cpp

moc_expressionhighlighter.cpp: expressionhighlighter.hpp
	/home/alex/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) expressionhighlighter.hpp -o moc_expressionhighlighter.cpp

moc_graphicaleditor.cpp: graphicaltoolkit.hpp \
		graphicalworkspace.hpp \
		graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp \
		graphicaleditor.hpp
	/home/alex/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) graphicaleditor.hpp -o moc_graphicaleditor.cpp

moc_graphicaltoolkit.cpp: graphicaltoolkit.hpp
	/home/alex/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) graphicaltoolkit.hpp -o moc_graphicaltoolkit.cpp

moc_graphicalworkspace.cpp: graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp \
		graphicalworkspace.hpp
	/home/alex/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) graphicalworkspace.hpp -o moc_graphicalworkspace.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/document-open.png \
		images/application-exit.png \
		images/document-new.png \
		images/kwordquiz.png \
		images/document-open-recent.png \
		images/document-save.png \
		images/text.png \
		images/document-save-as.png
	/home/alex/qtsdk-2009.05/qt/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp mainwindow.hpp \
		welcome.hpp \
		expressioneditor.hpp \
		graphicaleditor.hpp \
		graphicaltoolkit.hpp \
		graphicalworkspace.hpp \
		graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp \
		expressiontester.hpp \
		expressionhighlighter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.hpp \
		welcome.hpp \
		expressioneditor.hpp \
		graphicaleditor.hpp \
		graphicaltoolkit.hpp \
		graphicalworkspace.hpp \
		graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp \
		expressiontester.hpp \
		expressionhighlighter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

welcome.o: welcome.cpp welcome.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o welcome.o welcome.cpp

expressioneditor.o: expressioneditor.cpp expressioneditor.hpp \
		graphicaleditor.hpp \
		graphicaltoolkit.hpp \
		graphicalworkspace.hpp \
		graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp \
		expressiontester.hpp \
		expressionhighlighter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expressioneditor.o expressioneditor.cpp

expressiontester.o: expressiontester.cpp expressiontester.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expressiontester.o expressiontester.cpp

expressionhighlighter.o: expressionhighlighter.cpp expressionhighlighter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expressionhighlighter.o expressionhighlighter.cpp

graphicaleditor.o: graphicaleditor.cpp graphicaleditor.hpp \
		graphicaltoolkit.hpp \
		graphicalworkspace.hpp \
		graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicaleditor.o graphicaleditor.cpp

graphicaltoolkit.o: graphicaltoolkit.cpp graphicaltoolkit.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicaltoolkit.o graphicaltoolkit.cpp

graphicalworkspace.o: graphicalworkspace.cpp graphicalworkspace.hpp \
		graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicalworkspace.o graphicalworkspace.cpp

graphicalexpression.o: graphicalexpression.cpp graphicalexpression.hpp \
		groupinggraphicsitem.hpp \
		alternativesgraphicsitem.hpp \
		charrangegraphicsitem.hpp \
		repeatgraphicsitem.hpp \
		specialchargraphicsitem.hpp \
		textgraphicsitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicalexpression.o graphicalexpression.cpp

textgraphicsitem.o: textgraphicsitem.cpp textgraphicsitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textgraphicsitem.o textgraphicsitem.cpp

alternativesgraphicsitem.o: alternativesgraphicsitem.cpp alternativesgraphicsitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alternativesgraphicsitem.o alternativesgraphicsitem.cpp

groupinggraphicsitem.o: groupinggraphicsitem.cpp groupinggraphicsitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groupinggraphicsitem.o groupinggraphicsitem.cpp

charrangegraphicsitem.o: charrangegraphicsitem.cpp charrangegraphicsitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o charrangegraphicsitem.o charrangegraphicsitem.cpp

repeatgraphicsitem.o: repeatgraphicsitem.cpp repeatgraphicsitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o repeatgraphicsitem.o repeatgraphicsitem.cpp

specialchargraphicsitem.o: specialchargraphicsitem.cpp specialchargraphicsitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specialchargraphicsitem.o specialchargraphicsitem.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_welcome.o: moc_welcome.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_welcome.o moc_welcome.cpp

moc_expressioneditor.o: moc_expressioneditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_expressioneditor.o moc_expressioneditor.cpp

moc_expressiontester.o: moc_expressiontester.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_expressiontester.o moc_expressiontester.cpp

moc_expressionhighlighter.o: moc_expressionhighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_expressionhighlighter.o moc_expressionhighlighter.cpp

moc_graphicaleditor.o: moc_graphicaleditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicaleditor.o moc_graphicaleditor.cpp

moc_graphicaltoolkit.o: moc_graphicaltoolkit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicaltoolkit.o moc_graphicaltoolkit.cpp

moc_graphicalworkspace.o: moc_graphicalworkspace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicalworkspace.o moc_graphicalworkspace.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

